"""phase 1 initial schema

Revision ID: c96b3d3b7fda
Revises: 
Create Date: 2026-05-18 17:03:19.195880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c96b3d3b7fda'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('main_conversation_types',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('greeting_key', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('product_types',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('family', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('spec_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('use_cases',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('industry', sa.Text(), nullable=False),
    sa.Column('application', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('industry', 'application', name='uq_use_cases_industry_application')
    )
    op.create_table('conversations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('session_uuid', sa.UUID(), nullable=False),
    sa.Column('user_email', sa.Text(), nullable=True),
    sa.Column('user_company', sa.Text(), nullable=True),
    sa.Column('language', sa.CHAR(length=2), server_default='EN', nullable=False),
    sa.Column('main_type_code', sa.Text(), nullable=True),
    sa.Column('current_node', sa.Text(), nullable=True),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('ticket_id', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['main_type_code'], ['main_conversation_types.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_uuid')
    )
    op.create_index('ix_conversations_started_at', 'conversations', ['started_at'], unique=False)
    op.create_index('ix_conversations_user_email_present', 'conversations', ['user_email'], unique=False, postgresql_where=sa.text('user_email IS NOT NULL'))
    op.create_table('problem_types',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('product_type_id', sa.BigInteger(), nullable=True),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint('severity BETWEEN 1 AND 5', name='ck_problem_types_severity'),
    sa.ForeignKeyConstraint(['product_type_id'], ['product_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_type_id', 'code', name='uq_problem_types_product_code')
    )
    op.create_index(op.f('ix_problem_types_product_type_id'), 'problem_types', ['product_type_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('sku', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('product_type_id', sa.BigInteger(), nullable=True),
    sa.Column('specs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('datasheet_url', sa.Text(), nullable=True),
    sa.Column('cad_url', sa.Text(), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('status', sa.Text(), server_default='active', nullable=False),
    sa.ForeignKeyConstraint(['product_type_id'], ['product_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_index(op.f('ix_products_product_type_id'), 'products', ['product_type_id'], unique=False)
    op.create_table('use_case_product_types',
    sa.Column('use_case_id', sa.BigInteger(), nullable=False),
    sa.Column('product_type_id', sa.BigInteger(), nullable=False),
    sa.Column('fit_score', sa.SmallInteger(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.CheckConstraint('fit_score BETWEEN 1 AND 5', name='ck_use_case_product_types_fit_score'),
    sa.ForeignKeyConstraint(['product_type_id'], ['product_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['use_case_id'], ['use_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('use_case_id', 'product_type_id')
    )
    op.create_table('messages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('conversation_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('content_type', sa.Text(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('node', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_conversation_id_created_at', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_table('solutions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('problem_type_id', sa.BigInteger(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('body_markdown', sa.Text(), nullable=False),
    sa.Column('confidence', sa.SmallInteger(), nullable=False),
    sa.Column('escalate_if', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sop_url', sa.Text(), nullable=True),
    sa.Column('rma_template_url', sa.Text(), nullable=True),
    sa.CheckConstraint('confidence BETWEEN 1 AND 5', name='ck_solutions_confidence'),
    sa.ForeignKeyConstraint(['problem_type_id'], ['problem_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solutions_problem_type_id'), 'solutions', ['problem_type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_solutions_problem_type_id'), table_name='solutions')
    op.drop_table('solutions')
    op.drop_index('ix_messages_conversation_id_created_at', table_name='messages')
    op.drop_table('messages')
    op.drop_table('use_case_product_types')
    op.drop_index(op.f('ix_products_product_type_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_problem_types_product_type_id'), table_name='problem_types')
    op.drop_table('problem_types')
    op.drop_index('ix_conversations_user_email_present', table_name='conversations', postgresql_where=sa.text('user_email IS NOT NULL'))
    op.drop_index('ix_conversations_started_at', table_name='conversations')
    op.drop_table('conversations')
    op.drop_table('use_cases')
    op.drop_table('product_types')
    op.drop_table('main_conversation_types')
    # ### end Alembic commands ###
